spring:
  application:
    name: rain-ai-code-mother-backend
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rain_ai_code_mother?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: abc123
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cloud.raina.rainaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# 安全配置
security:
  password:
    salt: FavE0PsrBv97iXNIV/b3IA==