spring:
  application:
    name: rain-ai-code-mother-backend
  profiles:
    active: local
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rain_ai_code_mother?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: abc123
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # redis
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password:
#      ttl: 3600

server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cloud.raina.rainaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# 安全配置
# 密码盐值（可以用 generator包下的 SaltGenerator 来生成） 固定后请勿随意更换，会导致原有密码无法登录
#security:
#  password:
#    salt: FavE0PsrBv97iXNIV/b3IA==
# AI
#langchain4j:
#  open-ai:
#    chat-model:
#      base-url: https://api.deepseek.com
#      api-key: <Your API Key>
#      model-name: deepseek-chat
#      max-tokens: 8192
#      strict-json-schema: true
#      response-format: json_object
#      log-requests: true
#      log-responses: true
#    streaming-chat-model:
#      base-url: https://api.deepseek.com
#      api-key: <Your API Key>
#      model-name: deepseek-chat
#      max-tokens: 8192
#      log-requests: true
#      log-responses: true
# 添加 COS 对象存储配置（需要从腾讯云获取）
#cos:
#  client:
#    host: your-custom-domain.com
#    secretId: your-secret-id
#    secretKey: your-secret-key
#    region: ap-shanghai
#    bucket: your-bucket-name
# Pexels 图片搜索配置
#pexels:
#  api-key: <Your API Key>
# 阿里云 DashScope 配置
#dashscope:
#  api-key: <Your API Key>
#  image-model: wan2.2-t2i-flash
